In [11]:
!pip install boto3

Collecting boto3
  Downloading boto3-1.42.52-py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 2.7 MB/s eta 0:00:00a 0:00:01
Collecting jmespath<2.0.0,>=0.7.1
  Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Collecting s3transfer<0.17.0,>=0.16.0
  Downloading s3transfer-0.16.0-py3-none-any.whl (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 1.9 MB/s eta 0:00:00a 0:00:01
Collecting botocore<1.43.0,>=1.42.52
  Downloading botocore-1.42.52-py3-none-any.whl (14.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 6.2 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.10/site-packages (from botocore<1.43.0,>=1.42.52->boto3) (2.3.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.10/site-packages (from botocore<1.43.0,>=1.42.52->boto3) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.52->boto3) (1.17.0)
Installing collected packages: jmespath, botocore, s3transfer, boto3
Successfully installed boto3-1.42.52 botocore-1.42.52 jmespath-1.1.0 s3transfer-0.16.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [4]:
# Helper para criação de tabelas
from pyiceberg.partitioning import PartitionSpec
from pyiceberg.transforms import IdentityTransform
from pyiceberg.schema import Schema
from pyiceberg.io.pyarrow import pyarrow_to_schema
from pyiceberg.catalog import load_catalog
from pyiceberg.types import NestedField, StringType
from datetime import datetime
import polars as pl
import boto3
from io import BytesIO

# -------------------
# catálogo
# -------------------
catalog = load_catalog(
    "dev",
    uri="http://rest:8181",

    **{
        "s3.endpoint": "http://minio:9000",
        "s3.access-key-id": "minioadmin",
        "s3.secret-access-key": "minioadmin",
        "s3.path-style-access": "true",
    }
)

# -------------------
# s3 / minio
# -------------------
s3 = boto3.client(
    "s3",
    endpoint_url="http://minio:9000",
    aws_access_key_id="minioadmin",
    aws_secret_access_key="minioadmin",
)



def build_partition_spec(schema, partition_cols):
    # nenhum particionamento
    if not partition_cols:
        return PartitionSpec()

    fields = []

    for i, col in enumerate(partition_cols, start=1000):
        field = schema.find_field(col)

        if field is None:
            raise ValueError(f"Coluna '{col}' não existe no schema")

        fields.append(
            PartitionSpec.Field(
                source_id=field.field_id,
                field_id=i,
                transform=IdentityTransform(),
                name=col,
            )
        )

    return PartitionSpec(*fields)

def update_schema(table, arrow_schema):
    """
    Atualiza o schema da tabela Iceberg se houver colunas novas no DataFrame.
    
    Parameters
    ----------
    table : Iceberg table
        Tabela a ser verificada/atualizada
    arrow_schema : pyarrow.Schema
        Schema do DataFrame que será inserido
        
    Returns
    -------
    bool
        True se o schema foi atualizado, False caso contrário
    """ 
    # Atualiza o schema adicionando as novas colunas
    with table.update_schema() as update:
        update.union_by_name(arrow_schema)
    
    print(f"✔ schema atualizado")
    return True

def add_ingestion_metadata(df, file): 
    return df.with_columns(
        pl.lit(file).alias("_source_file"),
        pl.lit(datetime.utcnow().isoformat()).alias("_ingestion_time"), 
    )

def set_table(
    catalog,
    table_name: str,
    df,
    partition_cols=None,
    mode="append",
):
    """
    Cria ou carrega uma tabela Iceberg e escreve dados nela.

    Parameters
    ----------
    catalog : Iceberg catalog
    table_name : str
    df : polars.DataFrame
    partition_cols : list[str] | None
    mode : 'append' | 'overwrite'
    """

    # garante nomes limpos
    df = df.rename(lambda c: c.strip())

    arrow_table = df.to_arrow()
    arrow_schema = arrow_table.schema


    # -------------------
    # load or create
    # -------------------
    try:
        table = catalog.load_table(table_name)
        update_schema(table, arrow_schema)
        print(f"✔ tabela '{table_name}' carregada")

    except Exception as e:
        if "NoSuchTable" not in str(type(e)):
            raise  # erro real → não cria tabela
    
        print(f"⚙ criando tabela '{table_name}'")
    
        partition_spec = build_partition_spec(arrow_schema, partition_cols)
    
        table = catalog.create_table(
            identifier=table_name,
            schema=arrow_schema,
            partition_spec=partition_spec,
            properties={
                "write.format.default": "parquet",
                "write.parquet.compression-codec": "zstd",
                "schema.name-mapping.default": "true",
            },
        )
    # -------------------
    # write
    # -------------------
    if mode == "overwrite":
        table.overwrite(arrow_table)
    elif mode == "append":
        table.append(arrow_table)
    elif mode in ("reset"):
        print("⚠ full reset da tabela")
        table.delete("true")   # remove todos datafiles ativos
        table.append(arrow_table)

    print(f"✔ dados gravados ({mode})")

    return table

ModuleNotFoundError: No module named 'polars'

In [97]:
bucket = "raw"
candle_file_list = [
  "cryptocurrency/BTCUSDT-5m-2026-01.csv",
  "cryptocurrency/BTCUSDT-5m-2025-01.csv",
  "cryptocurrency/BTCUSDT-5m-2025-02.csv",
  "cryptocurrency/BTCUSDT-5m-2025-03.csv",
  "cryptocurrency/BTCUSDT-5m-2025-04.csv",
  "cryptocurrency/BTCUSDT-5m-2025-05.csv",
  "cryptocurrency/BTCUSDT-5m-2025-06.csv",
  "cryptocurrency/BTCUSDT-5m-2025-07.csv",
  "cryptocurrency/BTCUSDT-5m-2025-08.csv",
  "cryptocurrency/BTCUSDT-5m-2025-09.csv",
  "cryptocurrency/BTCUSDT-5m-2025-10.csv",
  "cryptocurrency/BTCUSDT-5m-2025-11.csv",
  "cryptocurrency/BTCUSDT-5m-2025-12.csv",
]

for key in candle_file_list:
    response = s3.get_object(Bucket=bucket, Key=key)
    buffer = BytesIO(response["Body"].read())
    
    df = pl.read_csv(buffer)
    # adiciona metadata de ingestão
    df = add_ingestion_metadata(df, key)
    
    arrow_table = df.to_arrow()
    table_name = 'bronze.crypto_candles'
    table = catalog.create_table_if_not_exists(table_name, schema=arrow_table.schema)
    table.overwrite(
        arrow_table, 
        overwrite_filter=EqualTo("_source_file", key)
    )

print("✔ RAW ingestão concluída")

/usr/local/lib/python3.10/site-packages/pyiceberg/table/__init__.py:651: UserWarning: Delete operation did not match any records
  warnings.warn("Delete operation did not match any records")

✔ RAW ingestão concluída

In [99]:
table = catalog.load_table("bronze.crypto_candles")
df = pl.from_arrow(table.scan().to_arrow())
df

shape: (114_048, 14)
┌─────────────┬─────────┬─────────┬─────────┬───┬─────────────┬────────┬─────────────┬─────────────┐
│ open_time   ┆ open    ┆ high    ┆ low     ┆ … ┆ taker_buy_q ┆ ignore ┆ _source_fil ┆ _ingestion_ │
│ ---         ┆ ---     ┆ ---     ┆ ---     ┆   ┆ uote_volume ┆ ---    ┆ e           ┆ time        │
│ i64         ┆ f64     ┆ f64     ┆ f64     ┆   ┆ ---         ┆ i64    ┆ ---         ┆ ---         │
│             ┆         ┆         ┆         ┆   ┆ f64         ┆        ┆ str         ┆ str         │
╞═════════════╪═════════╪═════════╪═════════╪═══╪═════════════╪════════╪═════════════╪═════════════╡
│ 17645472000 ┆ 90320.5 ┆ 90396.9 ┆ 89228.0 ┆ … ┆ 1.8349e8    ┆ 0      ┆ cryptocurre ┆ 2026-02-20T │
│ 00          ┆         ┆         ┆         ┆   ┆             ┆        ┆ ncy/BTCUSDT ┆ 16:16:25.71 │
│             ┆         ┆         ┆         ┆   ┆             ┆        ┆ -5m-2025…   ┆ 4790        │
│ 17645475000 ┆ 89771.3 ┆ 89783.6 ┆ 88900.0 ┆ … ┆ 2.1555e8    ┆ 0      ┆ cryptocurre ┆ 2026-02-20T │
│ 00          ┆         ┆         ┆         ┆   ┆             ┆        ┆ ncy/BTCUSDT ┆ 16:16:25.71 │
│             ┆         ┆         ┆         ┆   ┆             ┆        ┆ -5m-2025…   ┆ 4790        │
│ 17645478000 ┆ 89100.9 ┆ 89268.8 ┆ 88807.2 ┆ … ┆ 1.3552e8    ┆ 0      ┆ cryptocurre ┆ 2026-02-20T │
│ 00          ┆         ┆         ┆         ┆   ┆             ┆        ┆ ncy/BTCUSDT ┆ 16:16:25.71 │
│             ┆         ┆         ┆         ┆   ┆             ┆        ┆ -5m-2025…   ┆ 4790        │
│ 17645481000 ┆ 88887.8 ┆ 89056.2 ┆ 88591.0 ┆ … ┆ 1.3043e8    ┆ 0      ┆ cryptocurre ┆ 2026-02-20T │
│ 00          ┆         ┆         ┆         ┆   ┆             ┆        ┆ ncy/BTCUSDT ┆ 16:16:25.71 │
│             ┆         ┆         ┆         ┆   ┆             ┆        ┆ -5m-2025…   ┆ 4790        │
│ 17645484000 ┆ 88673.5 ┆ 88818.5 ┆ 88374.0 ┆ … ┆ 1.3509e8    ┆ 0      ┆ cryptocurre ┆ 2026-02-20T │
│ 00          ┆         ┆         ┆         ┆   ┆             ┆        ┆ ncy/BTCUSDT ┆ 16:16:25.71 │
│             ┆         ┆         ┆         ┆   ┆             ┆        ┆ -5m-2025…   ┆ 4790        │
│ …           ┆ …       ┆ …       ┆ …       ┆ … ┆ …           ┆ …      ┆ …           ┆ …           │
│ 17699025000 ┆ 79088.2 ┆ 79148.5 ┆ 78831.3 ┆ … ┆ 2.1816e7    ┆ 0      ┆ cryptocurre ┆ 2026-02-20T │
│ 00          ┆         ┆         ┆         ┆   ┆             ┆        ┆ ncy/BTCUSDT ┆ 16:16:08.37 │
│             ┆         ┆         ┆         ┆   ┆             ┆        ┆ -5m-2026…   ┆ 8327        │
│ 17699028000 ┆ 78871.1 ┆ 78989.3 ┆ 78724.0 ┆ … ┆ 1.7059e7    ┆ 0      ┆ cryptocurre ┆ 2026-02-20T │
│ 00          ┆         ┆         ┆         ┆   ┆             ┆        ┆ ncy/BTCUSDT ┆ 16:16:08.37 │
│             ┆         ┆         ┆         ┆   ┆             ┆        ┆ -5m-2026…   ┆ 8327        │
│ 17699031000 ┆ 78795.7 ┆ 78831.9 ┆ 78599.9 ┆ … ┆ 2.0547e7    ┆ 0      ┆ cryptocurre ┆ 2026-02-20T │
│ 00          ┆         ┆         ┆         ┆   ┆             ┆        ┆ ncy/BTCUSDT ┆ 16:16:08.37 │
│             ┆         ┆         ┆         ┆   ┆             ┆        ┆ -5m-2026…   ┆ 8327        │
│ 17699034000 ┆ 78706.7 ┆ 78909.3 ┆ 78693.8 ┆ … ┆ 1.2828e7    ┆ 0      ┆ cryptocurre ┆ 2026-02-20T │
│ 00          ┆         ┆         ┆         ┆   ┆             ┆        ┆ ncy/BTCUSDT ┆ 16:16:08.37 │
│             ┆         ┆         ┆         ┆   ┆             ┆        ┆ -5m-2026…   ┆ 8327        │
│ 17699037000 ┆ 78727.1 ┆ 78779.9 ┆ 78605.0 ┆ … ┆ 1.7862e7    ┆ 0      ┆ cryptocurre ┆ 2026-02-20T │
│ 00          ┆         ┆         ┆         ┆   ┆             ┆        ┆ ncy/BTCUSDT ┆ 16:16:08.37 │
│             ┆         ┆         ┆         ┆   ┆             ┆        ┆ -5m-2026…   ┆ 8327        │
└─────────────┴─────────┴─────────┴─────────┴───┴─────────────┴────────┴─────────────┴─────────────┘

In [75]:
table = catalog.load_table("bronze.crypto_candles")
df = pl.from_arrow(table.scan().to_arrow())
df = df.rename({"open_time": "timestamp"})
df = df.with_columns(
    timestamp = pl.from_epoch(pl.col("timestamp"), time_unit="ms"),
    symbol=pl.lit("BTCUSDT"),
    timeframe=pl.lit("5m"),
)

# pl.from_epoch(pl.col("timestamp"), time_unit="s")

Schema([('timestamp', Datetime(time_unit='ms', time_zone=None)),
        ('open', Float64),
        ('high', Float64),
        ('low', Float64),
        ('close', Float64),
        ('volume', Float64),
        ('close_time', Int64),
        ('quote_volume', Float64),
        ('count', Int64),
        ('taker_buy_volume', Float64),
        ('taker_buy_quote_volume', Float64),
        ('ignore', Int64),
        ('_source_file', String),
        ('_ingestion_time', String),
        ('symbol', String),
        ('timeframe', String)])

In [100]:

from pyiceberg.partitioning import PartitionSpec, PartitionField
from pyiceberg.expressions import EqualTo, In
from pyiceberg.transforms import IdentityTransform, MonthTransform
from pyiceberg.types import TimestampType, StringType, FloatType, DoubleType
from pyiceberg.io.pyarrow import schema_to_pyarrow

schema = Schema(
    NestedField(field_id=1,  name='timestamp',              field_type=TimestampType(), required=True),
    NestedField(field_id=2,  name='symbol',                 field_type=StringType(),    required=True),
    NestedField(field_id=3,  name='timeframe',              field_type=StringType(),    required=True),
    NestedField(field_id=4,  name='open',                   field_type=FloatType(),     required=True),
    NestedField(field_id=5,  name='high',                   field_type=FloatType(),     required=True),
    NestedField(field_id=6,  name='low',                    field_type=FloatType(),     required=True),
    NestedField(field_id=7,  name='close',                  field_type=FloatType(),     required=True),
    NestedField(field_id=8,  name='volume',                 field_type=FloatType(),     required=True),
    NestedField(field_id=9,  name='close_time',             field_type=DoubleType(),    required=False),
    NestedField(field_id=10, name='quote_volume',           field_type=FloatType(),     required=False),
    NestedField(field_id=11, name='count',                  field_type=DoubleType(),    required=False),
    NestedField(field_id=12, name='taker_buy_volume',       field_type=FloatType(),     required=False),
    NestedField(field_id=13, name='taker_buy_quote_volume', field_type=FloatType(),     required=False),
    NestedField(field_id=14, name='ignore',                 field_type=DoubleType(),    required=False),
    NestedField(field_id=15, name='_source_file',           field_type=StringType(),    required=True),
    NestedField(field_id=16, name='_ingestion_time',        field_type=StringType(),    required=True),
)
partition_spec = PartitionSpec(
    # Partição por Ativo (BTCUSDT, ETHUSDT...)
    PartitionField(
        source_id=2,       # id do campo 'symbol'
        field_id=1000,     # id sequencial para a partição
        transform=IdentityTransform(), 
        name="symbol"
    ),
    # Partição por Timeframe (1m, 5m, 1h...)
    PartitionField(
        source_id=3,       # id do campo 'timeframe'
        field_id=1001, 
        transform=IdentityTransform(), 
        name="timeframe"
    ),
    # Partição Temporal por Mês (Extrai o mês do timestamp automaticamente)
    PartitionField(
        source_id=1,       # id do campo 'timestamp'
        field_id=1002, 
        transform=MonthTransform(), 
        name="month"
    )
)
silver_table_name = "silver.cripto_currency"
catalog.create_table_if_not_exists(silver_table_name, schema=schema, partition_spec=partition_spec)

table = catalog.load_table("bronze.crypto_candles")
df = pl.from_arrow(table.scan().to_arrow())
df = df.rename({"open_time": "timestamp"})
df = df.with_columns(
    timestamp = pl.from_epoch(pl.col("timestamp"), time_unit="ms"),
    symbol=pl.lit("BTCUSDT"),
    timeframe=pl.lit("5m"),
)
files = df["_source_file"].unique().to_list()
iceberg_fields = [f.name for f in silver_table.schema().fields]
df = df.select(iceberg_fields)
silver_table = catalog.load_table(silver_table_name)
arrow_schema = schema_to_pyarrow(silver_table.schema())
arrow_table = df.to_arrow().cast(arrow_schema)
silver_table.overwrite(arrow_table, overwrite_filter=In("_source_file", files))

print("✅ Novos valores corretos")

✅ Novos valores corretos

In [86]:
catalog.load_table("silver.btcusdt5m").schema()

Schema(NestedField(field_id=1, name='timestamp', field_type=StringType(), required=False), NestedField(field_id=2, name='open', field_type=DoubleType(), required=False), NestedField(field_id=3, name='high', field_type=DoubleType(), required=False), NestedField(field_id=4, name='low', field_type=DoubleType(), required=False), NestedField(field_id=5, name='close', field_type=DoubleType(), required=False), NestedField(field_id=6, name='volume', field_type=DoubleType(), required=False), NestedField(field_id=7, name='_source_file', field_type=StringType(), required=False), NestedField(field_id=8, name='_ingestion_time', field_type=StringType(), required=False), schema_id=0, identifier_field_ids=[])

In [37]:
import polars as pl
table = catalog.load_table("silver.cripto_currency")
df = pl.scan_iceberg(table, storage_options=table.catalog.properties)
df = df.filter(
    (pl.col("symbol") == "BTCUSDT")
    & (pl.col("timeframe") == "5m")
)
df = df.sort("timestamp")

df = df.with_columns(
    ema_20=pl.col("close").ewm_mean(span=20),
    ema_200=pl.col("close").ewm_mean(span=200),
    volatility_20=pl.col("close").rolling_std(window_size=20),
    rsi=((pl.col("close") - pl.col("close").shift(1)).fill_null(0)
             .pipe(lambda diff: (diff.clip(0, None).ewm_mean(span=14) / 
                                 diff.clip(None, 0).abs().ewm_mean(span=14)))
             .pipe(lambda rs: 100 - (100 / (1 + rs)))
            )
)

df.limit(30).collect()

shape: (30, 20)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ timestamp  ┆ symbol  ┆ timeframe ┆ open      ┆ … ┆ ema_20    ┆ ema_200   ┆ volatilit ┆ rsi       │
│ ---        ┆ ---     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ y_20      ┆ ---       │
│ datetime[μ ┆ str     ┆ str       ┆ f32       ┆   ┆ f32       ┆ f32       ┆ ---       ┆ f32       │
│ s]         ┆         ┆           ┆           ┆   ┆           ┆           ┆ f32       ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2025-01-01 ┆ BTCUSDT ┆ 5m        ┆ 93548.796 ┆ … ┆ 93648.398 ┆ 93648.398 ┆ null      ┆ NaN       │
│ 00:00:00   ┆         ┆           ┆ 875       ┆   ┆ 438       ┆ 438       ┆           ┆           │
│ 2025-01-01 ┆ BTCUSDT ┆ 5m        ┆ 93648.296 ┆ … ┆ 93615.585 ┆ 93616.992 ┆ null      ┆ 0.0       │
│ 00:05:00   ┆         ┆           ┆ 875       ┆   ┆ 938       ┆ 188       ┆           ┆           │
│ 2025-01-01 ┆ BTCUSDT ┆ 5m        ┆ 93586.0   ┆ … ┆ 93621.320 ┆ 93621.773 ┆ null      ┆ 45.545464 │
│ 00:10:00   ┆         ┆           ┆           ┆   ┆ 312       ┆ 438       ┆           ┆           │
│ 2025-01-01 ┆ BTCUSDT ┆ 5m        ┆ 93631.203 ┆ … ┆ 93667.414 ┆ 93662.179 ┆ null      ┆ 80.108742 │
│ 00:15:00   ┆         ┆           ┆ 125       ┆   ┆ 062       ┆ 688       ┆           ┆           │
│ 2025-01-01 ┆ BTCUSDT ┆ 5m        ┆ 93781.0   ┆ … ┆ 93678.195 ┆ 93672.343 ┆ null      ┆ 59.901299 │
│ 00:20:00   ┆         ┆           ┆           ┆   ┆ 312       ┆ 75        ┆           ┆           │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2025-01-01 ┆ BTCUSDT ┆ 5m        ┆ 93724.703 ┆ … ┆ 93824.578 ┆ 93855.75  ┆ 194.36015 ┆ 38.704372 │
│ 02:05:00   ┆         ┆           ┆ 125       ┆   ┆ 125       ┆           ┆ 3         ┆           │
│ 2025-01-01 ┆ BTCUSDT ┆ 5m        ┆ 93660.5   ┆ … ┆ 93818.804 ┆ 93852.062 ┆ 196.70367 ┆ 47.997047 │
│ 02:10:00   ┆         ┆           ┆           ┆   ┆ 688       ┆ 5         ┆ 4         ┆           │
│ 2025-01-01 ┆ BTCUSDT ┆ 5m        ┆ 93767.898 ┆ … ┆ 93810.398 ┆ 93847.328 ┆ 200.21464 ┆ 45.61216  │
│ 02:15:00   ┆         ┆           ┆ 438       ┆   ┆ 438       ┆ 125       ┆ 5         ┆           │
│ 2025-01-01 ┆ BTCUSDT ┆ 5m        ┆ 93735.898 ┆ … ┆ 93797.851 ┆ 93840.945 ┆ 205.50070 ┆ 41.872963 │
│ 02:20:00   ┆         ┆           ┆ 438       ┆   ┆ 562       ┆ 312       ┆ 2         ┆           │
│ 2025-01-01 ┆ BTCUSDT ┆ 5m        ┆ 93685.898 ┆ … ┆ 93790.007 ┆ 93836.289 ┆ 208.14502 ┆ 45.356983 │
│ 02:25:00   ┆         ┆           ┆ 438       ┆   ┆ 812       ┆ 062       ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

dev (<class 'pyiceberg.catalog.rest.RestCatalog'>)